service: rssschool-node-import-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource: 
        - "arn:aws:::rssschool-node-import-service-s3"
    - Effect: "Allow"
      Action: 
        - "s3:*"
      Resource: 
        - "arn:aws:::rssschool-node-import-service-s3/*"


plugins:
  - serverless-webpack

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request: 
            parameters: 
              paths: 
                productId: true